# Copyright 2021 - 2023 Transflox LLC. All rights reserved.

apiVersion: v1
kind: Secret
metadata:
  name: velopay
  namespace: ${NAMESPACE_RAW}
type: Opaque
data:
  ENV: ${ENV}
  PRODUCTION: ${PRODUCTION}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  TENSOR_API_KEY: ${TENSOR_API_KEY}
